server:
  port: 8080

spring:
  datasource:
    hikari:
      max-lifetime: 177000
    url: jdbc:mysql://qvick.ctoieiwsyz2m.ap-northeast-2.rds.amazonaws.com:3306/qvick?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: qvick
    password: qvick1234!
  security:
    user:
      name: connect
      password: connect1234!

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

#  cache:
#    type: redis
#
#  data:
#    redis:
#      port: 6379
#      host: localhost

application:
  jwt:
    secretKey: ed4667fac1ca35c325e7298c05cd71e8f7d0ae5b46b48c3956cdc9b587ca5d0e
    expiration: 172800000    # 48시간
    refreshExpiration: 604800000 # 7일

firebase:
  sdk:
    path: firebase-sdk.json
  notification:
    non-check-title: ❗️
    non-check-message: 출석이 완료되지 않았습니다.

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0 #사용하는 버전을 명시
    path: /v3/api-docs #api 문서 확인 경로, localhost:8080/v3/api-docs 로 접근
  default-consumes-media-type: application/json #기본으로 설정되는 미디어타입 지정
  auto-tag-classes: true #오토 태그 기능 활성화
  groups:
    enabled: false #api 그룹 기능, default는 true 이나 당장 사용하지 않기에 false 로 지정

  swagger-ui:
    operationsSorter: method #method 기준으로 정렬, 그외 alpha 로 정렬 가능
    path: /swagger-ui.html