spring:
  datasource:
    url: jdbc:mysql://qvick-main.c7oiuo2k2gj8.ap-northeast-2.rds.amazonaws.com:3306/qvick?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: qvick
    password: qvick1234!

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

  cache:
    type: redis

  redis:
    port: 6379
    host: qvick

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 246755219900-sovfq7ee6o64n06hga1evp77jb7vkl2a.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          google:
            token-info: https://oauth2.googleapis.com/tokeninfo

application:
  jwt:
    secretKey: 25432A462D4A614E645267556A586E3272357538782F413F4428472B4B625065
    token:
      access-expiration-time: 43200000    # 12시간
      refresh-expiration-time: 604800000   # 7일

firebase:
  sdk:
    path: qvick-410805-firebase-adminsdk-69qs0-203e4ce808.json
  notification:
    non-check-title: ✅✅✅✅✅✅
    non-check-message: 출석하자~!!

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0 #사용하는 버전을 명시
    path: /v3/api-docs #api 문서 확인 경로, localhost:8080/v3/api-docs 로 접근

  default-consumes-media-type: application/json #기본으로 설정되는 미디어타입 지정
  auto-tag-classes: true #오토 태그 기능 활성화
  groups:
    enabled: false #api 그룹 기능, default는 true 이나 당장 사용하지 않기에 false 로 지정

  swagger-ui:
    operationsSorter: method #method 기준으로 정렬, 그외 alpha 로 정렬 가능
    path: /swagger-ui.html

server:
  port: 8080