spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Qvick?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: qvick
    password: qvick1234!

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

  cache:
    type: redis

  redis:
    port: 6379
    host: localhost

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 246755219900-6dvpou8m5lktd4jgfd23i3cv24f1pkq9.apps.googleusercontent.com
            client-secret: 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
        provider:
          google:
            token-info: https://oauth2.googleapis.com/tokeninfo

application:
  jwt:
    secretKey: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcwNDg2NjU4MiwiaWF0IjoxNzA0ODY2NTgyfQ.yKZ4QXFUdPAG2ftZtbScCUeWUvjbdKiL2LPcagXHyYU
    expiration: 900000
    refreshExpiration: 99999999

firebase:
  sdk:
    path: checkin-52ec9-firebase-adminsdk-ogjpu-a96b4a67f0.json
  notification:
    non-check-title: ✅✅✅✅✅✅
    non-check-message: 출석하자~!!

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0 #사용하는 버전을 명시
    path: /v3/api-docs #api 문서 확인 경로, localhost:8080/v3/api-docs 로 접근

  default-consumes-media-type: application/json #기본으로 설정되는 미디어타입 지정
  auto-tag-classes: true #오토 태그 기능 활성화
  groups:
    enabled: false #api 그룹 기능, default는 true 이나 당장 사용하지 않기에 false 로 지정

  swagger-ui:
    operationsSorter: method #method 기준으로 정렬, 그외 alpha 로 정렬 가능
    path: /swagger-ui.html

server:
  port: 8080
  servlet:
    context-path: /