spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Qvick?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: qvick
    password: qvick1234!

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

    cache:
      type: redis

  redis:
    port: 6379
    host: localhost

    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 846014004935-s8as4ndv858n1r1790tk1t3pd92v66rv.apps.googleusercontent.com
              client-secret: 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
          provider:
            google:
              token-info: https://oauth2.googleapis.com/tokeninfo

application:
  jwt:
    secretKey: 25432A462D4A614E645267556A586E3272357538782F413F4428472B4B625065
    expiration: 900000
    refreshExpiration: 99999999

firebase:
  sdk:
    path: checkin-52ec9-firebase-adminsdk-ogjpu-a96b4a67f0.json
  notification:
    non-check-title: ✅✅✅✅✅✅
    non-check-message: 출석하자~!!

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
